name: "Release Beta - 2GP"
description: "Upload a 2GP beta package version"
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sfdx-version:
    description: 'version of SFDX to install'
    required: false
  dev-hub-auth-url:
    description: 'SFDX auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org config to use'
    required: true
    default: release
  use-sf:
    description: 'Add option to use sf cli over sfdx cli'
    required: false
    default: 'False'
  snapshot-config-file:
    description: 'path to scratch org snapshot config'
    required: false
runs:
  using: "composite"
  steps:
      - name: Create Scratch Org From Snapshot
        if: "${{ inputs.snapshot-config-file }}"
        uses: MyClubHub/cumulusci-create-scratch-from-snapshot@v1
        with:
          dev-hub-auth-url: "${{ inputs.dev-hub-auth-url }}"
          org-name: "${{ inputs.org-name }}"
          snapshot-config-file: "${{ inputs.snapshot-config-file }}"
          org-config-file: "orgs/dev.json"
      - name: Release 2GP Beta
        uses: MyClubHub/cumulusci-run-flow-scratch@v3
        with:
          dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
          org-name: '${{ inputs.org-name }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          use-sf: '${{ inputs.use-sf }}'
          flow-name: release_2gp_beta
